# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myFlicks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'MBProgressHUD'

  # Pods for myFlicks

  target 'myFlicksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myFlicksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
